<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>20b4f0c7-5bf2-4103-8ee9-f087d5e3e943</elementGuidId>
    <imagePath></imagePath>
    <name>button_addTicketQuantity</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[2]/div[5]/div[2]/div[1]/div[1]/div[2]/div[2]/button[2]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@type,'button')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>[data-test=\"bigtix-test-quantity-select-add\"] &gt;&gt; nth=1</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>type</name>
        <type>Main</type>
        <value>button</value>
        <webElementGuid>7edd9175-74ef-447f-9f0d-d323edbf50a8</webElementGuid>
    </webElementProperties>
</WebElementEntity>