<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>037bd418-b4e0-4edc-ab53-9650f68b4a64</elementGuidId>
    <imagePath></imagePath>
    <name>link_eventLive</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/main[1]/div[1]/div[1]/div[2]/a[1]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>a &gt;&gt; internal:has-text=/^{{name}} {{name}} LIVE!{{date_time}}/</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>href</name>
        <type>Main</type>
        <value>/en/events/{{name}}-{{name}}-live/APPASIA1</value>
        <webElementGuid>7edd9175-74ef-447f-9f0d-d323edbf50a8</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>{{name}} LIVE!
        {{date_time}}</value>
        <webElementGuid>7edd9175-74ef-447f-9f0d-d323edbf50a8</webElementGuid>
    </webElementProperties>
</WebElementEntity>